# Generated by Django 3.2.13 on 2022-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='protein',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
