# Generated by Django 3.2.13 on 2022-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220621_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='Enter Ingredients', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(default='Enter Steps', max_length=400),
        ),
    ]
