# Generated by Django 3.2.13 on 2022-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220621_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Enter Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Enter Steps'),
        ),
    ]
